name: ci/cd

on:
  push:
    branches: [ master, release/*]
  pull_request:
    branches: [ master, release/*]

jobs:

  build:
    name: Build on LFE/OTP ${{ matrix.otp_version }} / ${{ matrix.os }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp_version: [21, 22, 23]
        os: [ubuntu-latest]

    container:
      image: erlang:${{ matrix.otp_version }}

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar3 compile
    - name: Xref Checks
      run: rebar3 xref
#    - name: Dialyzer
#      run: rebar3 dialyzer
#    - name: Run Tests
#      run: rebar3 ct -c
    - name: Test Coverage
      run: rebar3 do proper -c, cover -v --min_coverage=0
    - name: Notify CI/CD Slack Channel
      uses: innocarpe/actions-slack@v1
      with:
        status: ${{ job.status }}
        success_text: '✅ Build for ${{ github.repository }} on LFE/OTP ${{ matrix.otp_version }} succeeded! 😄🌈🐴🚢🐿 (commit id: ${{ github.sha }})'
        failure_text: '❌ Build for ${{ github.repository }} on LFE/OTP ${{ matrix.otp_version }} failed! 🤬💣🔥🚒 (commit id: ${{ github.sha }})'
        cancelled_text: '🚧 Build for ${{ github.repository }} on LFE/OTP ${{ matrix.otp_version }} was cancelled ... 😯🦡 (commit id: ${{ github.sha }})'
      env:
        GITHUB_TOKEN: ${{ secrets.CICD_BOT_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.CICD_BOT_WEBHOOK }}
      if: always()
